services:
  - type: web
    name: webhook-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://webhook:processor@webhook-processor.l0edef3.mongodb.net/?appName=webhook-processor
      - key: MONGO_DB
        value: webhooks_db
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: PROCESS_DELAY_SECONDS
        value: "30"
    # Dockerfile's CMD already runs uvicorn app.main:app ...

  - type: worker
    name: webhook-worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: >
      rq worker
      -u ${redis.REDIS_URL}
      transactions
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://webhook:processor@webhook-processor.l0edef3.mongodb.net/?appName=webhook-processor
      - key: MONGO_DB
        value: webhooks_db
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: PROCESS_DELAY_SECONDS
        value: "30"

  - type: redis
    name: redis
    plan: free
    # Render creates a Redis/Key-Value service and exposes REDIS_URL
